stages:
    - build
    - release

image: hub.0xdev.ru/infrastructure/dotnet-ci:3.1
variables:
    VERSION: 3.1.$CI_PIPELINE_ID-preview


build:
    stage: build
    script:
        - dotnet pack -c Release /p:Version=$VERSION -o $CI_PROJECT_DIR/nugets
        - mkdir -p Composer/Core
        - mkdir -p Composer/PQ
        - find $CI_PROJECT_DIR/src/Sitko.Core.Grpc/Proto -name "*.proto" | xargs /usr/local/bin/protoc --php_out=$CI_PROJECT_DIR/Composer/Core --grpc_out $CI_PROJECT_DIR/Composer/Core --proto_path=/opt/include --proto_path=$CI_PROJECT_DIR/src/Sitko.Core.Grpc/Proto --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_client_plugin
        - find $CI_PROJECT_DIR/src/Sitko.Core.PersistentQueue/Proto -name "*.proto" | xargs /usr/local/bin/protoc --php_out=$CI_PROJECT_DIR/Composer/PQ --proto_path=/opt/include --proto_path=$CI_PROJECT_DIR/src/Sitko.Core.PersistentQueue/Proto
    artifacts:
        paths:
            - $CI_PROJECT_DIR/nugets
            - $CI_PROJECT_DIR/Composer

release:
    stage: release
    when: manual
    allow_failure: false
    only:
        - master
    script:
        # push packages
        - find nugets -name *.nupkg -exec dotnet nuget push {} -s $NUGET_HOST -k $NUGET_API_KEY \;
        # auth ssh
        - mkdir -p ~/.ssh
        - cat "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        # configure git
        - git config --global user.email "deployer@gitlab.0xdev.ru"
        - git config --global user.name "Deployer"
        # push grpc php package
        - git clone ssh://git@gitlab.0xdev.ru:2224/Sitko/Core.Grpc.Php.git /tmp/php/grpc
        - mkdir -p /tmp/php/grpc/src
        - rm -rf /tmp/php/grpc/src/*
        - cp -a $CI_PROJECT_DIR/Composer/Core/* /tmp/php/grpc/src
        - echo v$VERSION > /tmp/php/grpc/VERSION
        - cd /tmp/php/grpc
        - git add .
        - git commit -m "Release $CI_PIPELINE_ID"
        - git tag -a v$VERSION -m "Release $CI_PIPELINE_ID"
        - git push
        - git push origin v$VERSION
        # upload common proto files to server
        - cd $CI_PROJECT_DIR
        - tar czf sitko.tgz -C src/Sitko.Core.Grpc/Proto .
        - mc config host add minio $S3_HOST $S3_ACCESS_KEY $S3_SECRET_KEY --api S3v4
        - mc cp sitko.tgz minio/$S3_BUCKET/proto/sitko.tgz
        # push pq php package
        - git clone ssh://git@gitlab.0xdev.ru:2224/Sitko/Core.PersistentQueue.Php.git /tmp/php/pq
        - mkdir -p /tmp/php/pq/src
        - rm -rf /tmp/php/pq/src/*
        - cp -a $CI_PROJECT_DIR/Composer/PQ/* /tmp/php/pq/src
        - echo v$VERSION > /tmp/php/pq/VERSION
        - cd /tmp/php/pq
        - git add .
        - git commit -m "Release $CI_PIPELINE_ID"
        - git tag -a v$VERSION -m "Release $CI_PIPELINE_ID"
        - git push
        - git push origin v$VERSION
