namespace Sitko.Core.Search.OpenSearch;

public static class OpenSearchHelper
{
    public static readonly string[] RusEnKeys =
    [
        "a => ф",
        "b => и",
        "c => с",
        "d => в",
        "e => у",
        "f => а",
        "g => п",
        "h => р",
        "i => ш",
        "j => о",
        "k => л",
        "l => д",
        "m => ь",
        "n => т",
        "o => щ",
        "p => з",
        "r => к",
        "s => ы",
        "t => е",
        "u => г",
        "v => м",
        "w => ц",
        "x => ч",
        "y => н",
        "z => я",
        "A => Ф",
        "B => И",
        "C => С",
        "D => В",
        "E => У",
        "F => А",
        "G => П",
        "H => Р",
        "I => Ш",
        "J => О",
        "K => Л",
        "L => Д",
        "M => Ь",
        "N => Т",
        "O => Щ",
        "P => З",
        "R => К",
        "S => Ы",
        "T => Е",
        "U => Г",
        "V => М",
        "W => Ц",
        "X => Ч",
        "Y => Н",
        "Z => Я",
        "[ => х",
        "] => ъ",
        "; => ж",
        "< => б",
        "> => ю"
    ];
}
